sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler:
        - gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      compiler:
        - clang
      osx_image: xcode9
  
before_install:
    - eval "${MATRIX_EVAL}"
  

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/Deps"
  - mkdir ${DEPS_DIR}
  
  # Download GCC 7.1
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      GCC_URL="http://data.banshee3d.com/gcc-7.1-trusty.zip"
      cd ${DEPS_DIR}
      mkdir gcc
      cd gcc
      wget --no-check-certificate --quiet - ${GCC_URL}
      unzip -q gcc-7.1-trusty.zip
      export PATH=${DEPS_DIR}/gcc/bin:$PATH
      export LD_LIBRARY_PATH=${DEPS_DIR}/gcc/lib:$LD_LIBRARY_PATH
      export LD_LIBRARY_PATH=${DEPS_DIR}/gcc/lib64:$LD_LIBRARY_PATH
    fi	

  # Download binutils 2.28
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      BINUTILS_URL="http://data.banshee3d.com/binutils-2.28-trusty.zip"
      cd ${DEPS_DIR}
      mkdir binutils
      cd binutils
      wget --no-check-certificate --quiet - ${BINUTILS_URL}
      unzip -q binutils-2.28-trusty.zip
      export PATH=${DEPS_DIR}/binutils/bin:${PATH}
      export LD_LIBRARY_PATH=${DEPS_DIR}/binutils/lib:$LD_LIBRARY_PATH
    fi	

  - cd ${TRAVIS_BUILD_DIR}

script:
 - rm -rf install
 - mkdir -p install/lib
 - mkdir Build
 - cd Build
 - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      CC=gcc CXX=g++ cmake -G "Unix Makefiles" -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++ -DINSTALL_OUTPUT_PATH="$PWD/../install" ../
    else
      cmake -G "Unix Makefiles" -DINSTALL_OUTPUT_PATH="$PWD/../install" ../
    fi
 - cmake --build . --config Release
 - cmake --build . --config Release --target install
 - cd ..
 - mv "$PWD/install/libxsc_core.a" "$PWD/install/lib/libxsc_core.a"
 - rm -rf Build
  
after_success:
  - today=`date +%d.%m.%Y`
  - buildName=${today}
  - filename=XShaderCompiler_${buildName}_${TRAVIS_OS_NAME}.tar.gz
  - find ./install -not -name "*.dbg" -not -name ".dwarf" -not -type d | cut -sd / -f 3- | tar -C ./install -czvf ${filename} -T -
  - curl -v --ftp-create-dirs -T ${filename} -u ${FTP_USER}:${FTP_PASSWORD} ${FTP_DESTINATION}