image: Visual Studio 2017
platform: x64
configuration: Release
clone_folder: C:\Projects\XShaderCompiler

environment:
  FTP_USER:
    secure: 6/QO2m0slpHVIaSvCgshSQ==
  FTP_PASSWORD:
    secure: 6XqoyKCbNNcaanDJ5p7M2w==
  FTP_HOST:
    secure: vkR/qaZuHZ7k7iZQBfLlNYJzx/+rzkhRlOloJq7o0mk=

build_script:
  - cmd: install.bat
  
after_build:
 - ps: $buildName = "$(Get-Date -format dd.MM.yyyy)"
 - ps: Set-AppveyorBuildVariable "BUILD_NAME" "$buildName"
 - cmd: 7z a XShaderCompiler_%BUILD_NAME%_win64.zip ./install/*

artifacts:
  - path: XShaderCompiler_%BUILD_NAME%_win64.zip
    name: XShaderCompiler_%BSF_BUILD_NAME%_win64
    type: zip

deploy:
  - provider: FTP
    protocol: ftp
    host: $(FTP_HOST)
    username: $(FTP_USER)
    password: $(FTP_PASSWORD)
    folder: XShaderCompilerBuilds
    application:
    active_mode: false
    beta: true
    debug: true
